services:
  db:
    image:  mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: cat8apple10wheel
      MYSQL_DATABASE: 3205-team
    ports:
      - "3316:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestJs-app-3205-team
    ports:
      - "30110:30110"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=30110
      - DATABASE_PORT=3306
      - DATABASE_HOST=localhost
      - DATABASE_USER=root
      - DATABASE_PASSWORD=cat8apple10wheel
      - DATABASE_DB=3205-team
      - LINK_LIFITIME=1d
    depends_on:
      - db
    networks:
      - app-network
    command: ["sh", "-c", "npm install && npm run build && npm start"]
  volumes:
    db_data:
      driver: local

  networks:
    app-network:
      driver: bridge